Public Enum GameLevel
	LEVEL_PARK1
	LEVEL_PARK2
	LEVEL_CLIMBING_TOP
	LEVEL_SEWERS1
	LEVEL_STREETS1
	LEVEL_MALL1
	LEVEL_MALL2
	LEVEL_MALL3
	LEVEL_MALL4
	LEVEL_BOOK_STORE
	LEVEL_HARDWARE_STORE
	LEVEL_ART_STORE
	LEVEL_ROOF
	LEVEL_MALL5
	LEVEL_MALL
End Enum
