'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("utuujin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_art_store() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_art_store", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_book_store() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_book_store", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_climbing_game_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_climbing_game_top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_color_game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_color_game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_hardware_store() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_hardware_store", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_hint_screen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_hint_screen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_magic_square() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_magic_square", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_parchment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_parchment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_rooftop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_rooftop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_space() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_space", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property lvl_shop() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("lvl_shop", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_artstore() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_artstore", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_book_store() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_book_store", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_climbing_top() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_climbing_top", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_hardware_store() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_hardware_store", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_mall1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_mall1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_mall2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_mall2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_mall3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_mall3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_mall4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_mall4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_mall5() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_mall5", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_park1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_park1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_park2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_park2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_rooftop() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_rooftop", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_sewers1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_sewers1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map_streets1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map_streets1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_btn_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_btn_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_btn_check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_btn_check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_btn_circle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_btn_circle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_btn_diamond() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_btn_diamond", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_btn_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_btn_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_btn_replay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_btn_replay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_btn_shape_backdrop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_btn_shape_backdrop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_btn_shift_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_btn_shift_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_btn_shift_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_btn_shift_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_btn_square() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_btn_square", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_btn_triangle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_btn_triangle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_cash_register_backdrop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_cash_register_backdrop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_climbing_game_backdrop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_climbing_game_backdrop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_item_battery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_item_battery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_item_crowbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_item_crowbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_item_hammer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_item_hammer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_item_nail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_item_nail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_item_screwdriver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_item_screwdriver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_item_wrench() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_item_wrench", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_paint_bucket() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_paint_bucket", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_shape_circle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_shape_circle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_shape_diamond() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_shape_diamond", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_shape_square() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_shape_square", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_shape_triangle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_shape_triangle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property snd_button_click() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_button_click", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property snd_correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property snd_error() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property snd_rocket_takeoff() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_rocket_takeoff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sprite_map() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sprite_map", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ttf_pixel_perfect() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ttf_pixel_perfect", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
